export const Deck = [
    { suit: "♦", number: 1, },
    { suit: "♦", number: 2, },
    { suit: "♦", number: 3, },
    { suit: "♦", number: 4, },
    { suit: "♦", number: 5, },
    { suit: "♦", number: 6, },
    { suit: "♦", number: 7, },
    { suit: "♦", number: 8, },
    { suit: "♦", number: 9, },
    { suit: "♦", number: 10, },
    { suit: "♦", number: 12, },
    { suit: "♦", number: 11, },
    { suit: "♦", number: 13, },
    { suit: "♣", number: 1, },
    { suit: "♣", number: 2, },
    { suit: "♣", number: 3, },
    { suit: "♣", number: 4, },
    { suit: "♣", number: 5, },
    { suit: "♣", number: 6, },
    { suit: "♣", number: 7, },
    { suit: "♣", number: 8, },
    { suit: "♣", number: 9, },
    { suit: "♣", number: 10, },
    { suit: "♣", number: 12, },
    { suit: "♣", number: 11, },
    { suit: "♣", number: 13, },
    { suit: "♠", number: 1, },
    { suit: "♠", number: 2, },
    { suit: "♠", number: 3, },
    { suit: "♠", number: 4, },
    { suit: "♠", number: 5, },
    { suit: "♠", number: 6, },
    { suit: "♠", number: 7, },
    { suit: "♠", number: 8, },
    { suit: "♠", number: 9, },
    { suit: "♠", number: 10, },
    { suit: "♠", number: 12, },
    { suit: "♠", number: 11, },
    { suit: "♠", number: 13, },
    { suit: "♥", number: 1, },
    { suit: "♥", number: 2, },
    { suit: "♥", number: 3, },
    { suit: "♥", number: 4, },
    { suit: "♥", number: 5, },
    { suit: "♥", number: 6, },
    { suit: "♥", number: 7, },
    { suit: "♥", number: 8, },
    { suit: "♥", number: 9, },
    { suit: "♥", number: 10, },
    { suit: "♥", number: 12, },
    { suit: "♥", number: 11, },
    { suit: "♥", number: 13, },
];

export const Suits = {
    diamond: "♦",
    club: "♣",
    spade: "♠",
    heart: "♥"
}