export const Deck = [
    { suit: "♦", number: 1, isFaceDown: false },
    { suit: "♦", number: 2, isFaceDown: false },
    { suit: "♦", number: 3, isFaceDown: false },
    { suit: "♦", number: 4, isFaceDown: false },
    { suit: "♦", number: 5, isFaceDown: false },
    { suit: "♦", number: 6, isFaceDown: false },
    { suit: "♦", number: 7, isFaceDown: false },
    { suit: "♦", number: 8, isFaceDown: false },
    { suit: "♦", number: 9, isFaceDown: false },
    { suit: "♦", number: 10, isFaceDown: false },
    { suit: "♦", number: 12, isFaceDown: false },
    { suit: "♦", number: 11, isFaceDown: false },
    { suit: "♦", number: 13, isFaceDown: false },
    { suit: "♣", number: 1, isFaceDown: false },
    { suit: "♣", number: 2, isFaceDown: false },
    { suit: "♣", number: 3, isFaceDown: false },
    { suit: "♣", number: 4, isFaceDown: false },
    { suit: "♣", number: 5, isFaceDown: false },
    { suit: "♣", number: 6, isFaceDown: false },
    { suit: "♣", number: 7, isFaceDown: false },
    { suit: "♣", number: 8, isFaceDown: false },
    { suit: "♣", number: 9, isFaceDown: false },
    { suit: "♣", number: 10, isFaceDown: false },
    { suit: "♣", number: 12, isFaceDown: false },
    { suit: "♣", number: 11, isFaceDown: false },
    { suit: "♣", number: 13, isFaceDown: false },
    { suit: "♠", number: 1, isFaceDown: false },
    { suit: "♠", number: 2, isFaceDown: false },
    { suit: "♠", number: 3, isFaceDown: false },
    { suit: "♠", number: 4, isFaceDown: false },
    { suit: "♠", number: 5, isFaceDown: false },
    { suit: "♠", number: 6, isFaceDown: false },
    { suit: "♠", number: 7, isFaceDown: false },
    { suit: "♠", number: 8, isFaceDown: false },
    { suit: "♠", number: 9, isFaceDown: false },
    { suit: "♠", number: 10, isFaceDown: false },
    { suit: "♠", number: 12, isFaceDown: false },
    { suit: "♠", number: 11, isFaceDown: false },
    { suit: "♠", number: 13, isFaceDown: false },
    { suit: "♥", number: 1, isFaceDown: false },
    { suit: "♥", number: 2, isFaceDown: false },
    { suit: "♥", number: 3, isFaceDown: false },
    { suit: "♥", number: 4, isFaceDown: false },
    { suit: "♥", number: 5, isFaceDown: false },
    { suit: "♥", number: 6, isFaceDown: false },
    { suit: "♥", number: 7, isFaceDown: false },
    { suit: "♥", number: 8, isFaceDown: false },
    { suit: "♥", number: 9, isFaceDown: false },
    { suit: "♥", number: 10, isFaceDown: false },
    { suit: "♥", number: 12, isFaceDown: false },
    { suit: "♥", number: 11, isFaceDown: false },
    { suit: "♥", number: 13, isFaceDown: false },
];

export const Suits = {
    diamond: "♦",
    club: "♣",
    spade: "♠",
    heart: "♥"
}